---
title: "Summary stats"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```

```{r}
# Preliminaries

# Load libraries
library(tidyverse)
library(patchwork) # from GitHub
library(png)
library(knitr)
library(broom)
library(here)

# Colour blind friendly palette
cbPalette <- c("#999999", "#E69F00", "#56B4E9", "#009E73", 
               "#F0E442", "#0072B2", "#D55E00", "#CC79A7")

# Helper functions for plotting
remove_y <- 
  theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank())

remove_x <-   
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank())
```

```{r}
# Read in all the specimen data
specimens <- read_csv(here("data/all-specimen-data.csv")) 
```

## How many male, female and unsexed specimens are there?

```{r}
  sum1 <-
  specimens %>%
  add_count(class) %>%
  add_count(class, sex) %>%
  select(class, sex, n, nn) %>%
  distinct() %>%
  mutate('%' = round(nn/n*100, 2))

  kable(sum1)
```

## Considering only sexed specimens, how many male and female specimens are there?

```{r}
  sum2 <-
  specimens %>%
  filter(!is.na(sex)) %>%
  add_count(class) %>%
  add_count(class, sex) %>%
  select(class, sex, n, nn) %>%
  distinct() %>%
  mutate('%' = round(nn/n*100, 2))

  kable(sum2)
```

## What about name bearing type specimens?
If we only consider name bearing type specimens the bias becomes more extreme. 

```{r}
  type_sum <-
  specimens2 %>%
  filter(!is.na(sex) & type == "Type") %>%
  add_count(class) %>%
  add_count(class, sex) %>%
  select(class, sex, n, nn) %>%
  distinct() %>%
  mutate('%' = round(nn/n*100, 2))

kable(type_sum)
```

### What if we split by the kind of type?

```{r}
  type_sum2 <-
  specimens2 %>%
  filter(!is.na(sex) & type != "NonType") %>%
  add_count(class, type) %>%
  add_count(class, sex, type) %>%
  select(class, sex, type, n, nn) %>%
  distinct() %>%
  mutate('%' = round(nn/n*100, 2))

kable(type_sum2)
```


```{r}
  type_sum3 <-
  specimens %>%
  filter(!is.na(sex) & !is.na(typeStatus)) %>%
  add_count(class, typeStatus) %>%
  add_count(class, sex, typeStatus) %>%
  select(class, sex, typeStatus, n, nn) %>%
  distinct() %>%
  mutate('%' = round(nn/n*100, 2))

kable(type_sum3)
```

```{r types_all, message = FALSE, echo = FALSE, fig.cap="Figure 1: Percentage of female (green) and male (blue) specimens and name bearing type specimens for birds and mammals."}
source(here("analyses/figure-types-all.R"))
plot_all + plot_types
```