---
title: "Variation through time"
output:
  word_document: default
  pdf_document: default
  html_document: default
---
  
  ```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```

```{r}
# Preliminaries

# Load libraries
library(tidyverse)
library(patchwork) # from GitHub
library(png)
library(knitr)
library(broom)
library(here)
library(ggfortify)

#install.packages("remotes")
#remotes::install_github("sckott/rphylopic")
library(rphylopic)

# Colour blind friendly palette
cbPalette <- c("#999999", "#E69F00", "#56B4E9", "#009E73", 
               "#F0E442", "#0072B2", "#D55E00", "#CC79A7")

# Helper functions for plotting
remove_y <- 
  theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank())

remove_x <-   
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank())
```

```{r}
# Read in all the specimen data
specimens <- read_csv(here("data/all-specimen-data.csv")) 
```

## How does the % of female specimens vary through time?

The mean percentage of female specimens varies across orders.

```{r}
# First set up dataset
ds_years <-
  specimens %>%
  filter(!is.na(sex)) %>%
  filter(!is.na(year)) %>%
  group_by(class) %>%
  add_count(binomial, year) %>%
  add_count(binomial, year, sex) %>%
  filter(n >= 50 & sex == "Female") %>%
  rename(female = nn) %>%
  mutate(male = n - female) %>%
  select(class, order, binomial, year, decade, n, female, male) %>%
  mutate(percentf = (female/n) * 100) %>%
  distinct()
```

## Fitting models
### Birds
```{r}
# Fitting the model for birds
ds_years_birds <- filter(ds_years, class == "Birds")
year_model_birds <- glm(cbind(female, male) ~ year, data = ds_years_birds, family = "binomial")
# Check for overdispersion
summary_mod_birds <- summary(year_model_birds)
summary_mod_birds$deviance / summary_mod_birds$df.resid 
# Look at outputs
tidy(anova(year_model_birds, test = "Chisq"))
summary(year_model_birds)

# Look at model diagnostics
autoplot(year_model_birds)
```

### Mammals
```{r}
# Fitting the model for mammals
ds_years_mammals <- filter(ds_years, class == "Mammals")
year_model_mammals <- glm(cbind(female, male) ~ year, data = ds_years_mammals, family = "binomial")

# Check for overdispersion
summary_mod_mammals <- summary(year_model_mammals)
summary_mod_mammals$deviance / summary_mod_mammals$df.resid 

# Look at outputs
tidy(anova(year_model_mammals, test = "Chisq"))
summary(year_model_mammals)

# Look at model diagnostics
autoplot(year_model_mammals)
```

## Plotting

```{r, all_years, message = FALSE, echo = FALSE, fig.cap = "Changes through time in mammals and birds with >50 specimens per species"}
source(here("analyses/figure-years-all.R"))
plot_year
```
