---
title: "Sexual size dimorphism"
output:
  html_document: default
  pdf_document: default
  word_document: default
---
  
  ```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```

```{r}
# Preliminaries

# Load libraries
library(tidyverse)
library(patchwork) # from GitHub
library(png)
library(knitr)
library(broom)
library(here)
library(ggfortify)
library(car)

#install.packages("remotes")
#remotes::install_github("sckott/rphylopic")
library(rphylopic)

# Colour blind friendly palette
cbPalette <- c("#999999", "#E69F00", "#56B4E9", "#009E73", 
               "#F0E442", "#0072B2", "#D55E00", "#CC79A7")

# Helper functions for plotting
remove_y <- 
  theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank())

remove_x <-   
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank())
```

```{r}
# Read in all the specimen data and body size data
specimens <- read_csv(here("data/all-specimen-data.csv")) 
extra <- read_csv(here("data/all-extra-data.csv"))
```

## Does sexual size dimorphism influence % female specimens?

```{r}
ds <-
  specimens %>%
  filter(!is.na(sex)) %>%
  group_by(class) %>%
  add_count(binomial) %>%
  add_count(binomial, sex) %>%
  filter(n >= 100 & sex == "Female") %>%
  mutate(percent = (nn/n)*100) %>%
  rename(female = nn) %>%
  mutate(male = n - female) %>%
  select(class, order, binomial, percent, male, female) %>%
  distinct()
```


```{r}
# Merge body size data with the specimen data
# Exclude anything that doesn't have specimen data
ds_ssd <- left_join(ds, extra)
```

## Fitting models
### Birds
```{r}
# Fitting the model for birds
ds_ssd_birds <- filter(ds_ssd, class == "Birds")
ssd_model_birds <- glm(cbind(female, male) ~ log(SSD), data = ds_ssd_birds, family = "binomial")
# Check for overdispersion
summary_mod_birds <- summary(ssd_model_birds)
summary_mod_birds$deviance / summary_mod_birds$df.resid 

# Quasi model
ssd_model_birds <- glm(cbind(female, male) ~ log(SSD), 
                       data = ds_ssd_birds, family = "quasibinomial")

# Look at outputs
tidy(Anova(ssd_model_birds, test = "F"))
summary(ssd_model_birds)

# Look at model diagnostics
autoplot(ssd_model_birds)
```

```{r}
# More complex models involving order and male_mass
#1.  With order as an interaction
ssd_model_birds2 <- glm(cbind(female, male) ~ log(SSD)*order, 
                        data = ds_ssd_birds, family = "quasibinomial")

# Look at outputs
tidy(Anova(ssd_model_birds2, test = "F"))
summary(ssd_model_birds2)

#2.  With mass and order as an interaction
ssd_model_birds3 <- glm(cbind(female, male) ~ log(SSD)*log(male_mass)*order, 
                        data = ds_ssd_birds, family = "quasibinomial")

# Look at outputs
tidy(Anova(ssd_model_birds3, test = "F"))
summary(ssd_model_birds3)

#3. Just mass and order
ssd_model_birds4 <- glm(cbind(female, male) ~ log(male_mass)*order, 
                        data = ds_ssd_birds, family = "quasibinomial")

# Look at outputs
tidy(Anova(ssd_model_birds4, test = "F"))
summary(ssd_model_birds4)

```

```{r}

for(i in 1:length(levels(as.factor(ds_ssd_birds$order)))){
  dsx <- filter(ds_ssd_birds, order == levels(as.factor(order))[i])
  if(length(dsx$order) > 10){
  modelx <- glm(cbind(female, male) ~ log(SSD), 
            data = dsx, family = "quasibinomial")
  print(paste(levels(as.factor(ds_ssd_birds$order))[i], tidy(Anova(modelx, test = "F"))[[5]][1]))
  }
}
```

```{r}

for(i in 1:length(levels(as.factor(ds_ssd_mammals$order)))){
  dsx <- filter(ds_ssd_mammals, order == levels(as.factor(order))[i])
  if(length(dsx$order) > 10){
  modelx <- glm(cbind(female, male) ~ log(SSD), 
            data = dsx, family = "quasibinomial")
  print(paste(levels(as.factor(ds_ssd_mammals$order))[i], tidy(Anova(modelx, test = "F"))[[5]][1]))
  }
}
```
### Mammals
```{r}
# Fitting the model for mammals
ds_ssd_mammals <- filter(ds_ssd, class == "Mammals")
ssd_model_mammals <- glm(cbind(female, male) ~ log(SSD), data = ds_ssd_mammals, family = "binomial")

# Check for overdispersion
summary_mod_mammals <- summary(ssd_model_mammals)
summary_mod_mammals$deviance / summary_mod_mammals$df.resid 

ssd_model_mammals <- glm(cbind(female, male) ~ log(SSD), 
                         data = ds_ssd_mammals, family = "quasibinomial")

# Look at outputs
tidy(Anova(ssd_model_mammals, test = "F"))
summary(ssd_model_mammals)

# Look at model diagnostics
autoplot(ssd_model_mammals)
```

```{r}
# More complex models involving order and male_mass
#1.  With order as an interaction
ssd_model_mammals2 <- glm(cbind(female, male) ~ log(SSD)*order, 
                        data = ds_ssd_mammals, family = "quasibinomial")

# Look at outputs
tidy(Anova(ssd_model_mammals2, test = "F"))
summary(ssd_model_mammals2)


#2.  With mass and order as an interaction
ssd_model_mammals3 <- glm(cbind(female, male) ~ log(SSD)*log(male_mass)*order, 
                        data = ds_ssd_mammals, family = "quasibinomial")

# Look at outputs
tidy(Anova(ssd_model_mammals3, test = "F"))
summary(ssd_model_mammals3)

#3. Just mass and order
ssd_model_mammals4 <- glm(cbind(female, male) ~ log(male_mass)*order, 
                        data = ds_ssd_mammals, family = "quasibinomial")

# Look at outputs
tidy(Anova(ssd_model_mammals4, test = "F"))
summary(ssd_model_mammals4)
```

## Plotting
### Birds

```{r, bird_ssd, message = FALSE, echo = FALSE, fig.cap = "The relationship between % female and the degree of sexual size dimorphism. The dotted line at zero shows where there is no sexual size dimorphism. Values > 0 indicate males are bigger, values < 0 indicate that females are larger."}
source(here("analyses/figure-ssd-all.R"))
(pass | hum | wood)/(parrot | shore | pigeon)

```

```{r}
names(ds_ssd)
ds_ssd_birdsX <- filter(ds_ssd_birds, order != "Passeriformes")

ggplot(ds_ssd_mammals, aes(x = log(SSD), y = percent, color = order)) +
  geom_point() 

x1 <-  filter(ds_ssd_birds, male_mass <= 100)
x2 <-  filter(ds_ssd_birds, male_mass > 300)

ssd_m1 <- glm(cbind(female, male) ~ log(SSD), data = ds_ssd_birdsX, family = "binomial")
ssd_m1 <- glm(cbind(female, male) ~ log(SSD), data = x1, family = "binomial")
ssd_m2 <- glm(cbind(female, male) ~ log(SSD), data = x2, family = "binomial")

# Look at outputs
summary(ssd_m1)$coef[2]
summary(ssd_m2)$coef[2]

```
## Plotting
### Mammals

```{r, mammal_ssd, message = FALSE, echo = FALSE, fig.cap = "The relationship between % female and the degree of sexual size dimorphism. The dotted line at zero shows where there is no sexual size dimorphism. Values > 0 indicate males are bigger, values < 0 indicate that females are larger."}
source(here("analyses/figure-ssd-all.R"))
(rodent | bat | sor)/(carn|primate|artio)
```
