---
title: "Plumage and ornaments"
output:
  word_document: default
  pdf_document: default
  html_document: default
---
  
  ```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```

```{r}
# Preliminaries

# Load libraries
library(tidyverse)
library(patchwork) # from GitHub
library(png)
library(knitr)
library(broom)
library(here)
library(ggfortify)
library(car)

#install.packages("remotes")
#remotes::install_github("sckott/rphylopic")
library(rphylopic)

# Colour blind friendly palette
cbPalette <- c("#999999", "#E69F00", "#56B4E9", "#009E73", 
               "#F0E442", "#0072B2", "#D55E00", "#CC79A7")

# Helper functions for plotting
remove_y <- 
  theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank())

remove_x <-   
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank())
```

```{r, message = FALSE}
# Read in all the specimen data and extra data
specimens <- read_csv(here("data/all-specimen-data.csv"))
extra <- read_csv(here("data/all-extra-data.csv"))
```

## Extract % female specimens

```{r}
ds <-
  specimens %>%
  filter(!is.na(sex)) %>%
  group_by(class) %>%
  add_count(binomial, name = "n") %>%
  add_count(binomial, sex, name = "nn") %>%
  filter(n >= 100 & sex == "Female") %>%
  mutate(percent = (nn/n)*100) %>%
  rename(female = nn) %>%
  mutate(male = n - female) %>%
  select(class, order, binomial, percent, male, female) %>%
  distinct()
```


```{r}
# Merge data with the specimen data
# Exclude anything that doesn't have specimen data
ds_plumage <- left_join(ds, extra)

# Split into birds and mammals for models
ds_plumage_birds <- filter(ds_plumage, class == "Birds")

# Extract mammals 
ds_ornament_mammals <- 
  ds_plumage %>%
  filter(class == "Mammals")

# Remove ossicles
ds_ornament_mammals2 <- 
  ds_ornament_mammals %>%
  filter(is.na(feature) | feature != "ossicle")
  
```

## How many species and specimens are in the models?

```{r}
  sum_bird <-
  ds_plumage_birds %>%
  filter(!is.na(male_plumage) & !is.na(female_plumage)) %>%
  select(class, binomial, male, female) %>%
  distinct() %>%
  summarise(species = n(), spec = sum(male, female),
            male = sum(male), female = sum(female))

  kable(sum_bird)
```

```{r}
  sum_mamm <-
  ds_ornament_mammals %>%
  filter(!is.na(ornamentation)) %>%
  select(class, binomial, male, female) %>%
  distinct() %>%
  summarise(species = n(), spec = sum(male, female),
            male = sum(male), female = sum(female))

  kable(sum_mamm)
```

## Fitting models
## Do sexual ornaments influence % female specimens?
### Passeriformes plumage
This is only for Passeriformes where we have data on plumage colours for males and females.

```{r}
# Fitting the model for birds
# Model is overdispersed so use quasi binomial model
plumage_model_birds <- glm(cbind(female, male) ~ log(plumageD), 
                           data = ds_plumage_birds, family = "quasibinomial")

# Look at model diagnostics
autoplot(plumage_model_birds)

# Look at outputs
tidy(Anova(plumage_model_birds, test = "F"))
summary(plumage_model_birds)
```

### Ornaments in mammals

```{r}
# Fitting the model for mammals
# Model is overdispersed so use quasi binomial model
ornament_model_mammals <- glm(cbind(female, male) ~ ornamentation, data = 
                                ds_ornament_mammals, family = "quasibinomial")
# Note that the interaction with order is not significant

# Look at model diagnostics
autoplot(ornament_model_mammals)

# Look at outputs
tidy(Anova(ornament_model_mammals, test = "F"))
#summary(ornament_model_mammals)
```
```{r}
# What about for type of ornament? Remove ossicles here as there is only one species with them
feature_model_mammals <- glm(cbind(female, male) ~ feature, data = 
                                ds_ornament_mammals2, family = "quasibinomial")
# Note that the interaction with order is not significant

# Look at model diagnostics
autoplot(feature_model_mammals)

# Look at outputs
tidy(Anova(feature_model_mammals, test = "F"))
summary(feature_model_mammals)
```
```{r}
# What about for whether males or females have the ornament?
sex_model_mammals <- glm(cbind(female, male) ~ ornamentedsex, data = 
                                ds_ornament_mammals, family = "quasibinomial")
# Note that the interaction with order is not significant

# Look at model diagnostics
autoplot(sex_model_mammals)

# Look at outputs
tidy(Anova(sex_model_mammals, test = "F"))
summary(sex_model_mammals)
```

```{r}
# What about for whether males or females have the ornament and what sort it is?
# Again cut out ossicles
both_model_mammals <- glm(cbind(female, male) ~ feature * ornamentedsex, data = 
                                ds_ornament_mammals2, family = "quasibinomial")
# Note that the interaction with order is not significant

# Look at model diagnostics
autoplot(both_model_mammals)

# Look at outputs
tidy(Anova(both_model_mammals, test = "F"))
summary(both_model_mammals)
```

```{r}
# How about just for horns or tusks?
orn <-
  ds_ornament_mammals2 %>%
  mutate(horn = ornamentation) %>%
  mutate(horn = ifelse(feature == "tusk" | is.na(feature), "Absent", horn)) %>%
  mutate(tusk = ornamentation) %>%
  mutate(tusk = ifelse(feature == "horn" | is.na(feature), "Absent", tusk)) %>%
  mutate(artio = ifelse(order == "Artiodactyla", "artio", "not"))

horn_model_mammals <- glm(cbind(female, male) ~ horn, data = 
                                orn, family = "quasibinomial")

# Look at model diagnostics
autoplot(horn_model_mammals)

# Look at outputs
tidy(Anova(horn_model_mammals, test = "F"))
summary(horn_model_mammals)

tusk_model_mammals <- glm(cbind(female, male) ~ tusk, data = 
                                orn, family = "quasibinomial")

# Look at model diagnostics
autoplot(tusk_model_mammals)

# Look at outputs
tidy(Anova(tusk_model_mammals, test = "F"))
summary(tusk_model_mammals)
```

```{r}
# Can we identify if being an artiodactyl or having ornaments is the key thing? (no)
artio_model_mammals <- glm(cbind(female, male) ~ artio + ornamentation, data = 
                                orn, family = "quasibinomial")

# Look at model diagnostics
autoplot(artio_model_mammals)

# Look at outputs
tidy(Anova(artio_model_mammals, test = "F"))
summary(artio_model_mammals)
```

```{r}
# What about just looking at species with horns and classing the rest as absent?
justhorns <- filter(orn, horn == "Present")

horn_model <- glm(cbind(female, male) ~ extremesex, data = 
                                justhorns, family = "quasibinomial")

# Look at model diagnostics
autoplot(horn_model)

# Look at outputs
tidy(anova(horn_model, test = "F"))
summary(horn_model)
```
