---
title: "Looking more closely at Apodiformes"
output:
  word_document: default
  pdf_document: default
  html_document: default
---
  
  ```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```

```{r}
# Preliminaries

# Load libraries
library(tidyverse)
library(patchwork) # from GitHub
library(png)
library(knitr)
library(broom)
library(here)
library(ggfortify)

#install.packages("remotes")
#remotes::install_github("sckott/rphylopic")
library(rphylopic)

# Colour blind friendly palette
cbPalette <- c("#999999", "#E69F00", "#56B4E9", "#009E73", 
               "#F0E442", "#0072B2", "#D55E00", "#CC79A7")

# Helper functions for plotting
remove_y <- 
  theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank())

remove_x <-   
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank())
```

```{r, warning = FALSE, message = FALSE}
# Read in all the specimen data
specimens <- read_csv(here("data/all-specimen-data.csv"))

# Read in Apodiformes taxonomy data 
taxonomy <- read_csv(here("data/taxonomy-apodiformes.csv"))
```

## Select just Apodiformes from specimen data

```{r}
# Set up dataset with % female
ds_apo <-
  specimens %>%
  filter(!is.na(sex)) %>%
  filter(order == "Apodiformes") %>%
  add_count(binomial, name = "n") %>%
  add_count(binomial, sex, name = "nn") %>%
  filter(n >= 100 & sex == "Female") %>%
  rename(female = nn) %>%
  mutate(male = n - female) %>%
  select(class, order, binomial, n, female, male) %>%
  mutate(percentf = (female/n) * 100) %>%
  distinct()

## Add taxonomy data
ds_apo <-
  ds_apo %>%
  left_join(taxonomy, by = "binomial")
```

## Split by families
```{r}
sum_apo <-  
  ds_apo %>%
  group_by(family) %>%
  summarise('n species' = length(unique(binomial)),
           'n specimens' = sum(n),
           '% female' = round(median(percentf), 2),
           'se female' = sqrt(var(percentf)/length(percentf)))

kable(sum_apo)
```


```{r}
  ggplot(ds_apo, aes(percentf, fill = family, colour = family)) +
  theme_bw(base_size = 14) +
  geom_density(alpha = 0.5) +
  xlab("% female") +
  xlim(0, 100) +
  theme_bw(base_size = 14) +
  geom_vline(xintercept = 50, linetype = 2) +
  scale_colour_manual(values = c(cbPalette[c(4,5,8)])) +
  scale_fill_manual(values = c(cbPalette[c(4,5,8)])) +
  theme(legend.title = element_blank(),
        legend.position = c(0.85, 0.85))

ggsave(here("figures/apodiforme-families.png"), height = 100, units = "mm")

```