---
title: "Wild sex ratio comparisons"
output:
  word_document: default
  pdf_document: default
  html_document: default
---
  
  ```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```

```{r, warning = FALSE, message = FALSE}
# Preliminaries

# Load libraries
library(tidyverse)
library(patchwork) # from GitHub
library(png)
library(knitr)
library(broom)
library(here)
library(ggfortify)
library(car)

#install.packages("remotes")
#remotes::install_github("sckott/rphylopic")
library(rphylopic)

# Colour blind friendly palette
cbPalette <- c("#999999", "#E69F00", "#56B4E9", "#009E73", 
               "#F0E442", "#0072B2", "#D55E00", "#CC79A7")

# Helper functions for plotting
remove_y <- 
  theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank())

remove_x <-   
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank())
```

```{r, warning = FALSE, message = FALSE}
# Read in all the specimen data
specimens <- read_csv(here("data/all-specimen-data.csv"))

# Read in szekely data
asr <- read_csv(here("data/szekely2014.csv"))
```

## Select data and calculate ASR

```{r}
# Set up dataset with % female
ds_ratio <-
  specimens %>%
  filter(!is.na(sex)) %>%
  filter(class == "Birds") %>%
  add_count(binomial, name = "n") %>%
  add_count(binomial, sex, name = "nn") %>%
  filter(n >= 100 & sex == "Female") %>%
  rename(female = nn) %>%
  mutate(male = n - female) %>%
  select(class, order, family, binomial, n, female, male) %>%
  mutate(asr_museum = male/(male+female)) %>%
  distinct()

```

## Compare with wild data

```{r}
ratio <- 
  asr %>%
  left_join(ds_ratio, by = c("Species" = "binomial")) %>%
  select(Species, ASR, asr_museum) %>%
  mutate(diff = ASR - asr_museum) %>%
  drop_na()

kable(ratio)
```

## What % of ASR are more male biased in museums?
```{r}
length(which(ratio$diff < 0))/length(ratio$diff) * 100
```

## What % of ASR are more male biased in wild?
```{r}
length(which(ratio$diff > 0))/length(ratio$diff) * 100
```

```{r}
ggplot(ratio, aes(x = ASR, y = asr_museum)) +
  geom_point() +
  geom_abline(slope = 1, intercept = 0, linetype = 2, col = "red") +
  geom_vline(xintercept = 0.5, linetype = 3) +
  geom_hline(yintercept = 0.5, linetype = 3) +
  xlim(0, 1) +
  ylim(0,1) +
  xlab("wild ASR") +
  ylab("museum ASR") +
  theme_bw(base_size = 14)

ggsave(here("figures/wild-sex-ratios.png"), height = 100, units = "mm")

```


## Compare with paired t-test
```{r}
ratio2 <-
  ratio %>%
  gather(key = type, value = ratio, ASR, asr_museum)
  
t.test(ratio ~ type, data = ratio2, paired = TRUE)
```
```